### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by vadi2** [darealshinji/linuxdeploy-plugin-checkrt#1]
It's not immediately obvious how to actually use this in conjunction with linuxdeployqt.AppImage to make an AppImage that works with a newer libstdc++ version.

**Comment by darealshinji** [comment]
Inside the AppDir create a directory `usr/optional/libstdc++` and place the `libstdc++.so.6` library inside. Then replace the AppRun binary with the patched one from the release section.

If you used gcc compiled from source you'll have to add the stdc++ library from that compiler version.

I should probably add a better description on how to do that.

**Comment by darealshinji** [comment]
By the way if you want to build an AppImage using a `.yml` file here's an example on how to make use of the patched AppRun binary:

``` yaml
app: Aegisub

ingredients:
  packages:
    #- aegisub-l10n  # localisation doesn't work (requires patching the source)
  dist: stable
  sources:
    - deb http://ftp.debian.org/debian/ stable main universe

script:
  - DEB=libstdc++6_6.3.0-18_amd64.deb
  - wget -O ../$DEB -c "http://ftp.debian.org/debian/pool/main/g/gcc-6/$DEB"
  - dpkg-deb -x ../$DEB .
  - mkdir -p ./usr/optional/libstdc++
  - mv ./usr/lib/x86_64-linux-gnu/libstdc++.so.6* ./usr/optional/libstdc++
  - find ./usr -name libstdc++.so.6*-gdb.py -delete
  - rm -rf ./AppRun ./usr/lib/x86_64-linux-gnu/x264-10bit
  - wget -O AppRun "https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64"
  - chmod a+x AppRun
```
